[25/05/2025 00:22:24] Erro: System.Net.Http.HttpRequestException: Ocorreu um erro ao enviar a solicitação. ---> System.Net.WebException: Impossível conectar-se ao servidor remoto ---> System.Net.Sockets.SocketException: Uma operação de soquete foi tentada em um host inacessível 172.217.29.46:443
   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Fim do rastreamento de pilha de exceções internas ---
   em System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   em System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- Fim do rastreamento de pilha de exceções internas ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   em CadastroBanco.Backup.<CallAppsScriptApi>d__9.MoveNext() na C:\Users\samue.DESKTOP-LR09IQF\OneDrive\Documentos\GitHub\projeto-entensao\CadastroProduto\CadastroBanco\Backup.cs:linha 105
